title: "Alexi Karuna"
description: "Freelance SRE, Backend Engineer, AI/LLM Systems"
url: "https://alexikaruna.com"

remote_theme: "riggraz/no-style-please"

plugins:
  - jekyll-include-cache

# Optional - disable search if not needed
minimal_mistakes_skin: "default"
